/*
 * This file is automatically generated by "mkversion"
 */

#include "mm-patchlevel.h"
#define MM_MAJOR 0
#define MM_MINOR 90
#define MM_EDIT 87
#define MM_VERSION "Columbia MM, version 0.90.4(87)"
#define MM_COMPILED "by howie@watsol on 21 Nov 97 10:00am"
