Jag har pratat lite med mina närmaste chefer och alla väntar sig att
stoppet ska hävas ++snart, men ingen vet när. Vi tar in konsulter
dock, så om du har en firma att använda så kan du kontakta
torbjorn.cederlof@teliasonera.com och fråga om han har något hål att
stoppa in dig i, skicka med CV och hälsa från mig så han vet vem han
ska fråga. På det viset så kan du få in inkomst och bägge parter
kan nosa lite på varandra, vilket kanske är bra.

Kan det vara något?
