From: Steveo <moparholic@hotmail-nospam-.com>
Subject: Re: Install this important update from the M$ Corp.
Newsgroups: alt.sports.football.pro.ariz-cardinals,alt.sports.football.pro.cleve-browns,alt.sports.football.pro.sea-seahawks,alt.sports.football.pro.ne-patriots,alt.sports.football.pro.sf-49ers,alt.sports.football.pro.cinci-bengals,alt.sys.pdp10,alt.sys.mac.newuser-h
Date: 12 Nov 2003 20:23:38 GMT
Organization: Mounds Of Power And Revs

                                             .:\:/:.
         +-------------------+             .:\:\:/:/:.
         |   PLEASE DO NOT   |            :.:\:\:/:/:.:
         |  FEED THE TROLLS! |           :=.' -   - '.=:
         |                   |           '=(\ 9   9 /)='
         |                   |              (  (_)  )
         |                   |              /`-vvv-'\
         +-------------------+             /  TROLL  \
                 |  |        @@@          / /|,,,,,|\ \
                 |  |        @@@         /_//  /^\  \\_\
   @x@@x@        |  |         |/         WW(  (   )  )WW
   \||||/        |  |        \|           __\,,\ /,,/__
    \||/         |  |         |          (______Y______)
/\/\/\/\/\/\/\/\//\/\\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\/\
